### PR TITLE
Add installation animation

### PR DESCRIPTION
**Pull request by gpotter2**
Demo over: https://gpotter2.github.io/secdev.github.io/

It's basically the same as https://github.com/secdev/scapy#interactive-shell

### CODE REVIEW

**Comment by guedou** [comment]
Can't we link the one from `secdev/scapy` instead? That will simplify updates to the video.

**Comment by gpotter2** [comment]
It appears we'll have to do the opposite: host the file here.
GitHub doesn't render SVG animations that are linked with a relative path (README only):
https://github.com/gpotter2/scapy/blob/gallery/README.md
But does render the ones with an absolute one:
https://github.com/nbedos/termtosvg

**Comment by guedou** [comment]
It sounds good!

**Comment by gpotter2** [comment]
@guedou I've updated the SVG following https://github.com/secdev/scapy/issues/2040

**Pull request merged**
