### PR TITLE
Migrate to Jekyll

### PR DESCRIPTION
**Pull request by gpotter2**
Hi !

Here is a proposal of an auto-generated website using the `Jekyll` module. It's the mostly updated and easy-to-use I could find.

### CODE REVIEW

**Comment by guedou** [comment]
This looks awesome! Why did not you use Jekyll instead?

My preference goes for the non-black themes.

**Comment by gpotter2** [comment]
I have used it in the past. Do you want me to switch to Jekyll?, it’s pretty easy.
My preference is the last one.

Is it possible to link scapy.net to, for instance, a “public” folder in this repository ?

**Comment by guedou** [comment]
> I have used it in the past. Do you want me to switch to Jekyll, it’s pretty
> easy.
> My preference is the last one.

I would also prefer to use Jekyll. We would have nothing to do to
publish the content besides pushing a PR.

 
> Is it possible to link scapy.net to, for instance, a “public” folder in this
> repository ?

What do you mean?

**Comment by guedou** [comment]
It works fine, jekyll only complains that there is no favicon.ico.

Is it normal that no theme is used, and that syntax highlighting does not work?

I am fine with merging it as it is =)

**Comment by gpotter2** [comment]
Updated with the "beautiful-jekyll" theme you had provided in https://github.com/secdev/scapy/issues/1339

Should now be better.

**Comment by guedou** [comment]
Sorry, I am not good at using ruby. I had to look at tutorial to build the site locally. It looks awesome!

**Comment by guedou** [comment]
It is now live on https://scapy.net ! 
There is an issue with the logo, I think that the url in the config file should be "scapy.net"

Also, github detected an issue with the nogiri Gem.

**Pull request merged**
