### PR TITLE
Use "remote-theme" & add scapy-awesome

### PR DESCRIPTION
**Pull request by gpotter2**
This allows to not store the theme ourselves, but rather use the foreign one.

- use "remote-theme" (currently pointing to gpotter2/beautiful-jekyll, waiting for https://github.com/daattali/beautiful-jekyll/pull/590
- add "[awesome-scapy](https://github.com/gpotter2/awesome-scapy)" submodule

### CODE REVIEW

**Review by guedou — APPROVED** [review]
Cool PR!

You should transfer the ownership of awesome-scapy to secdev. I will contribute my list of tools =)

Do yo want me to wait for this change to be done before merging this PR?

**Comment by gpotter2** [comment]
I moved it but lost all admin permissions on it.
If you could fix that it would be great. Same for this repo actually

**Comment by guedou** [comment]
Done on both repo.

**Review by p-l- — APPROVED** [review]

**Comment by p-l-** [comment]
Should we merge now or wait and change the remote-theme?

**Comment by gpotter2** [comment]
Let's try to have it fixed first

**Comment by gpotter2** [comment]
The PR was merged and the theme updated. This should be ready to go

**Pull request merged**
